from django.urls import path
from .views import (
    GestionDashboardView,
    GestionParrillaListView,
    GestionParrillaCreateView,
    GestionParrillaUpdateView,
    GestionParrillaDeleteView,
    GestionPromocionListView,
    GestionPromocionCreateView,
    GestionPromocionUpdateView,
    GestionPromocionDeleteView,
    GestionCategoriaListView,
    GestionCategoriaCreateView,
    GestionCategoriaUpdateView,
    GestionCategoriaDeleteView,
    GestionUbicacionListView,
    GestionUbicacionCreateView,
    GestionUbicacionUpdateView,
    GestionUbicacionDeleteView,
    GestionResenaListView,
    GestionResenaCreateView,
    GestionResenaUpdateView,
    GestionResenaDeleteView,
    GestionUsuarioListView,
    GestionUsuarioCreateView,
    GestionUsuarioUpdateView,
    GestionUsuarioDeleteView,
)

app_name = "gestion"

urlpatterns = [
    path("", GestionDashboardView.as_view(), name="dashboard"),

    path("parrillas/", GestionParrillaListView.as_view(), name="parrillas_lista"),
    path("parrillas/crear/", GestionParrillaCreateView.as_view(), name="parrillas_crear"),
    path("parrillas/<int:pk>/editar/", GestionParrillaUpdateView.as_view(), name="parrillas_editar"),
    path("parrillas/<int:pk>/eliminar/", GestionParrillaDeleteView.as_view(), name="parrillas_eliminar"),
    path("promociones/", GestionPromocionListView.as_view(), name="promociones_lista"),
    path("promociones/crear/", GestionPromocionCreateView.as_view(), name="promociones_crear"),
    path("promociones/<int:pk>/editar/", GestionPromocionUpdateView.as_view(), name="promociones_editar"),
    path("promociones/<int:pk>/eliminar/", GestionPromocionDeleteView.as_view(), name="promociones_eliminar"),

    path("categorias/", GestionCategoriaListView.as_view(), name="categorias_lista"),
    path("categorias/crear/", GestionCategoriaCreateView.as_view(), name="categorias_crear"),
    path("categorias/<int:pk>/editar/", GestionCategoriaUpdateView.as_view(), name="categorias_editar"),
    path("categorias/<int:pk>/eliminar/", GestionCategoriaDeleteView.as_view(), name="categorias_eliminar"),
    path("categorias/", GestionCategoriaListView.as_view(), name="categorias_lista"),
    path("categorias/crear/", GestionCategoriaCreateView.as_view(), name="categorias_crear"),
    path("categorias/<int:pk>/editar/", GestionCategoriaUpdateView.as_view(), name="categorias_editar"),
    path("categorias/<int:pk>/eliminar/", GestionCategoriaDeleteView.as_view(), name="categorias_eliminar"),
    path("ubicaciones/", GestionUbicacionListView.as_view(), name="ubicaciones_lista"),
    path("ubicaciones/crear/", GestionUbicacionCreateView.as_view(), name="ubicaciones_crear"),
    path("ubicaciones/<int:pk>/editar/", GestionUbicacionUpdateView.as_view(), name="ubicaciones_editar"),
    path("ubicaciones/<int:pk>/eliminar/", GestionUbicacionDeleteView.as_view(), name="ubicaciones_eliminar"),
    path("resenas/", GestionResenaListView.as_view(), name="resenas_lista"),
    path("resenas/crear/", GestionResenaCreateView.as_view(), name="resenas_crear"),
    path("resenas/<int:pk>/editar/", GestionResenaUpdateView.as_view(), name="resenas_editar"),
    path("resenas/<int:pk>/eliminar/", GestionResenaDeleteView.as_view(), name="resenas_eliminar"),
        path("usuarios/", GestionUsuarioListView.as_view(), name="usuarios_lista"),
    path("usuarios/crear/", GestionUsuarioCreateView.as_view(), name="usuarios_crear"),
    path("usuarios/<int:pk>/editar/", GestionUsuarioUpdateView.as_view(), name="usuarios_editar"),
    path("usuarios/<int:pk>/eliminar/", GestionUsuarioDeleteView.as_view(), name="usuarios_eliminar"),
]
