# Generated by Django 5.2.7 on 2025-11-25 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('parrillas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='es_duenio_parrilla',
            field=models.BooleanField(default=False, help_text='Indica si este usuario actúa como dueño oficial de una parrilla dentro del sitio.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='parrilla_asociada',
            field=models.OneToOneField(blank=True, help_text='Parrilla de la cual este usuario es dueño. Solo se usa si es_duenio_parrilla es True.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profile', to='parrillas.parrilla'),
        ),
    ]
