# Generated by Django 5.0 on 2025-11-15 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parrillas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(choices=[(1, '🌭 1 choripán (muy mala experiencia)'), (2, '🌭🌭 2 choripanes (floja)'), (3, '🌭🌭🌭 3 choripanes (zafa)'), (4, '🌭🌭🌭🌭 4 choripanes (muy buena)'), (5, '🌭🌭🌭🌭🌭 5 choripanes (excelente)')], help_text='Elegí de 1 a 5 choripanes (1 = peor, 5 = mejor).')),
                ('comentario', models.TextField(help_text='Comentario del usuario sobre la parrilla.')),
                ('is_active', models.BooleanField(default=True, help_text='Permite ocultar la reseña sin borrarla.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='parrillas.parrilla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.UniqueConstraint(fields=('usuario', 'parrilla'), name='unique_resena_usuario_parrilla'),
        ),
    ]
