# Generated by Django 5.2.7 on 2025-11-25 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaResena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Respuesta pública de la parrilla a la reseña.')),
                ('valoracion', models.CharField(choices=[('happy', '😊 Respuesta positiva a la reseña'), ('sad', '☹️ Respuesta negativa / disconforme con la reseña')], help_text='Valoración de la reseña (carita feliz o triste).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(help_text='Usuario dueño de la parrilla que responde a la reseña. A nivel de lógica, vamos a validar que coincida con la parrilla.', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_resenas', to=settings.AUTH_USER_MODEL)),
                ('resena', models.OneToOneField(help_text='Reseña del usuario a la que responde la parrilla.', on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='resenas.resena')),
            ],
            options={
                'verbose_name': 'Respuesta a reseña',
                'verbose_name_plural': 'Respuestas a reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
