# Generated by Django 5.2.7 on 2025-11-25 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0002_respuestaresena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaresena',
            name='resena',
            field=models.OneToOneField(help_text='Reseña del usuario a la que responde la parrilla.', on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_parrilla', to='resenas.resena'),
        ),
        migrations.AlterField(
            model_name='respuestaresena',
            name='valoracion',
            field=models.CharField(choices=[('happy', '😊'), ('sad', '☹️')], help_text='Valoración de la reseña (carita feliz o triste).', max_length=10),
        ),
    ]
