# Generated by Django 5.0 on 2025-11-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(help_text='Ciudad donde se encuentra la parrilla. Ej: Buenos Aires.', max_length=100)),
                ('nombre_barrio', models.CharField(help_text='Barrio o zona. Ej: Caballito, Palermo, Centro.', max_length=100)),
                ('latitud', models.FloatField(blank=True, help_text='Latitud opcional. Usada para mapas.', null=True)),
                ('longitud', models.FloatField(blank=True, help_text='Longitud opcional. Usada para mapas.', null=True)),
                ('google_maps_url', models.URLField(blank=True, help_text='Enlace pegado a mano de Google Maps (opcional).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
