# Generated by Django 5.0 on 2026-05-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='zona',
            field=models.CharField(blank=True, choices=[('CABA', 'CABA'), ('GBA_NORTE', 'GBA Norte'), ('GBA_OESTE', 'GBA Oeste'), ('GBA_SUR', 'GBA Sur')], help_text='Zona general para filtros del sitio. Ej: CABA, GBA Norte, GBA Oeste, GBA Sur.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre_barrio',
            field=models.CharField(help_text='Barrio o zona. Ej: Caballito, Palermo, Avellaneda.', max_length=100),
        ),
    ]
