# Generated by Django 5.0 on 2025-11-16 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parrillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título de la promo. Ej: '2x1 en choripán'.", max_length=150)),
                ('descripcion', models.TextField(help_text='Descripción completa de la promoción o evento.')),
                ('precio_promocional', models.DecimalField(blank=True, decimal_places=2, help_text='Precio promocional (opcional). Ej: 2500.00', max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la cual la promo está vigente.')),
                ('fecha_fin', models.DateField(help_text='Fecha hasta la cual la promo está vigente.')),
                ('is_active', models.BooleanField(default=True, help_text='Permite desactivar la promo sin borrarla.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='parrillas.parrilla')),
            ],
        ),
    ]
