# Generated by Django 5.0 on 2025-11-15 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre de la parrilla. Ej: 'El Chori de Caballito'.", max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la parrilla, tipo de comida, estilo, etc.', null=True)),
                ('direccion', models.CharField(help_text="Dirección completa. Ej: 'Av. Rivadavia 1234'.", max_length=200)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de la parrilla (opcional).', max_length=50, null=True)),
                ('sitio_web', models.URLField(blank=True, help_text='Sitio web o enlace a redes sociales (opcional).', null=True)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='parrillas/')),
                ('promedio_puntaje', models.FloatField(blank=True, help_text='Puntaje promedio basado en reseñas (1 a 5 choripanes).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Permite desactivar la parrilla sin borrarla.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parrillas', to='categorias.categoria')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parrillas', to='ubicaciones.ubicacion')),
            ],
        ),
    ]
