# Generated by Django 5.0 on 2025-11-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría. Ej: Gourmet, Barrio, Feria.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Identificador único corto para URLs y filtros. Ej: gourmet', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la categoría.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
